Teploobmen/TeploobmenWeb/Models/ErrorViewModel.cs
namespace TeploobmenWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teploobmen/TeploobmenWeb/Models/HomeIndexViewModel.cs
using Microsoft.AspNetCore.Mvc;
using TeploobmenWeb.Data;

namespace TeploobmenWeb.Models
{
    public class HomeIndexViewModel 
    {
        public Variant? Variant { get; set; }
        public List<Variant> Variants { get; set; }
    }
}

Teploobmen/TeploobmenWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using TeploobmenLibrary;
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;

namespace TeploobmenWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _context;
        private int _userId;

        public HomeController(ILogger<HomeController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            int.TryParse(User.FindFirst("Id")?.Value, out _userId);
        }
        [HttpPost]
        public IActionResult Result(TeploobmenInput input)
        {
            //Сохранение варианта
            if (!string.IsNullOrEmpty(input.Name))
            {
                var existVariant = _context.Variants.FirstOrDefault(x => x.Name == input.Name);

                if (existVariant != null)
                {
                    // Обновление варианта
                    existVariant.h = input.h;
                    existVariant.t1 = input.t1;
                    existVariant.T = input.T;
                    existVariant.s = input.s;
                    existVariant.C = input.C;
                    existVariant.Gm = input.Gm;
                    existVariant.Cm = input.Cm;
                    existVariant.d = input.d;
                    existVariant.aV = input.aV;

                    _context.Variants.Update(existVariant);
                    _context.SaveChanges();
                }
                else
                {
                    //добавление варианта
                    var variant = new Variant
                    {
                        Name = input.Name,
                        h = input.h,
                        t1 = input.t1,
                        T = input.T,
                        s = input.s,
                        C = input.C,
                        Gm = input.Gm,
                        Cm = input.Cm,
                        d = input.d,
                        aV = input.aV,
                        UserId = _userId,
                        CreatedAt = DateTime.Now
                    };

                    _context.Variants.Add(variant);
                    _context.SaveChanges();
                }
            }
            //Выполнение расчёта
            var lib = new Teploobmen(input);
            var result = lib.calc();
            if (ModelState.IsValid)
                return View(result);
            TempData["message"] = $"Заполните все поля";
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Index(int? variantId)
        {
            var viewModel = new HomeIndexViewModel();

            if (variantId != null)
            {
                viewModel.Variant = _context.Variants
                    .Where(x => x.UserId == _userId || x.UserId == 0)
                    .FirstOrDefault(x => x.Id == variantId);
            }

            viewModel.Variants = _context.Variants
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .ToList();

            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Remove(int? variantId)
        {
            var variant = _context.Variants
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .FirstOrDefault(x => x.Id == variantId);

            if (variant != null)
            {
                _context.Variants.Remove(variant);
                _context.SaveChanges();

                TempData["message"] = $"Вариант {variant.Name} удален.";
            }
            else
            {
                TempData["message"] = $"Вариант не найден.";
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teploobmen/TeploobmenWeb/Controllers/LoginController.cs
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using TeploobmenLibrary;

namespace TeploobmenWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly ApplicationContext _context;

        public LoginController(ILogger<LoginController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext; 
        }

        [HttpPost]
        public async Task<IActionResult> Index(string email, string password)
        {
            var user = _context.Users.FirstOrDefault(x => x.Email == email && x.Password == password);
            if (user != null)
            {
                var claims = new List<Claim> {
                    new Claim("Id", user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.Email),
                    //new Claim(ClaimTypes.Role, "user"),
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }
    }
}

Teploobmen/TeploobmenWeb/Controllers/RegistrController.cs
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using TeploobmenLibrary;

namespace TeploobmenWeb.Controllers
{
    public class RegistrController : Controller
    {
        private readonly ILogger<RegistrController> _logger;
        private readonly ApplicationContext _context;

        public RegistrController(ILogger<RegistrController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        
        public IActionResult Index(TeploobmenInput input)
        {
            if (!string.IsNullOrEmpty(input.Email))
            {
                
                var user = new User
                {
                    Email = input.Email,
                    Password = input.Password
                };
                _context.Users.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");

            }
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teploobmen/TeploobmenWeb/Controllers/UserController.cs
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TeploobmenLibrary;

namespace TeploobmenWeb.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Teploobmen/TeploobmenWeb/Views/Home/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Расчёт";
}

@if (!string.IsNullOrEmpty(TempData["message"]?.ToString()))
{
    <div class="alert alert-danger">
        @TempData["message"]
    </div>
}
<form action="/Home/Result" method="post">
    Номер варианта:
    <input name="Name" value="@Model.Variant?.Name" autocomplete="off" data-val="true" />
    <p>
        Высота слоя (м):
        <input name="h" value="@Model.Variant?.h" autocomplete="off" data-val="true" />
        Нач. температура окатышей (градусы):
        <input name="t1" value="@Model.Variant?.t1" autocomplete="off" data-val="true" />
        Нач. температура воздуха (градусы):
        <input name="T" value="@Model.Variant?.T" autocomplete="off" data-val="true" />
    </p>
    <p>
        Скорость вохдуха на свободное сечение шахты (м/с):
        <input name="s" value="@Model.Variant?.s" autocomplete="off" data-val="true" />
        Средняя теплоёмкость воздуха при 200 градусах (кДж/(кг*К):
        <input name="C" value="@Model.Variant?.C" autocomplete="off" data-val="true" />
    </p>
    Расход окатышей:
    <input name="Gm" value="@Model.Variant?.Gm" autocomplete="off" data-val="true" />
    Теплоёмкость окатышей:
    <input name="Cm" value="@Model.Variant?.Cm" autocomplete="off" data-val="true" />
    <p><p>
        Диаметр аппарата (м):
        <input name="d" value="@Model.Variant?.d" autocomplete="off" data-val="true" />
        Объемный коэффициент теплоотдачи:
        <input name="aV" value="@Model.Variant?.aV" autocomplete="off" data-val="true" />
    </p>
    <p>
        <button type="submit"> Рассчитать</button>
    </p>
</form>
<h2>Варианты расчетов</h2>
<table class="table table-border">
    <tr>
        <td>Название варианта</td>
        <td>Высота слоя (м)</td>
        <td>Нач. температура окатышей (градусы):</td>
        <td>Нач. температура воздуха (градусы):</td>
        <td>Скорость вохдуха на свободное сечение шахты (м/с)</td>
        <td>Средняя теплоёмкость воздуха при 200 градусах (кДж/(кг*К)</td>
        <td>Расход окатышей:</td>
        <td>Теплоёмкость окатышей:</td>
        <td>Диаметр аппарата (м):</td>
        <td>Объемный коэффициент теплоотдачи:</td>
        <td></td>
    </tr>

    @foreach (var variant in Model.Variants)
    {
        <tr>
            <td>@variant.Name</td>
            <td>@variant.h</td>
            <td>@variant.t1</td>
            <td>@variant.T</td>
            <td>@variant.s</td>
            <td>@variant.C</td>
            <td>@variant.Gm</td>
            <td>@variant.Cm</td>
            <td>@variant.d</td>
            <td>@variant.aV</td>
            <td>
                <a href="/Home/Index/?variantId=@variant.Id">Открыть</a>
                <a href="/Home/Remove/?variantId=@variant.Id">Удалить</a>
            </td>
        </tr>

    }
</table>

Teploobmen/TeploobmenWeb/Views/Home/Result.cshtml
@model TeploobmenOutput
@{
    ViewData["Title"] = "Расчёт";
}

@if (Model != null)
{
    <diw> <p>Площадь основания S= @Model.square</p> </diw>
    <diw> <p>Отношение теплоемкостей потоков m= @Model.relationship</p></diw>
    <diw> <p>Полная относительная высота слоя Y0= @Model.full_height <p /> </diw>
    <h2>Таблица результатов</h2>
    <table class="table">
        <tr>
            <td rowspan="2">&nbsp;</td>
            <td colspan="13"> координаты y, м/td>
        </tr>
        <tr>
            @foreach (var a in Model.position)
            {
                <td>@a</td>
            }
        </tr>
        <tr>
            <td> Y </td>
            @foreach (var b in Model.Y)
            {
                <td>@b</td>
            }
        </tr>

        <tr>
            <td> 1-exp(((m-1)Y)/m) </td>
            @foreach (var c in Model.X)
            {
                <td>@c</td>
            }
        </tr>
        <tr>
            <td> 1-m*exp(((m-1)Y)/m) </td>
            @foreach (var d in Model.Z)
            {
                <td>@d</td>
            }
        </tr>
        <tr>
            <td> V </td>
            @foreach (var e in Model.V)
            {
                <td>@e</td>
            }
        </tr>
        <tr>
            <td> O </td>
            @foreach (var f in Model.O)
            {
                <td>@f</td>
            }
        </tr>
        <tr>
            <td> t окатышей </td>
            @foreach (var g in Model.t)
            {
                <td>@g</td>
            }
        </tr>
        <tr>
            <td> T пара </td>
            @foreach (var h in Model.T)
            {
                <td>@h</td>
            }
        </tr>
        <tr>
            <td> Разность температур </td>
            @foreach (var i in Model.diff_temp)
            {
                <td>@i</td>
            }
        </tr>
    </table>

    <div class="Chart">
        <canvas id="myChart"></canvas>
    </div>
    <script src="/js/chart.js"></script>

    <script>
        const ctx = document.getElementById('myChart');

        const data = {
            labels: @Json.Serialize(Model.position),
            datasets: [
                {
                    label: 'Температура метала',
                    data: @Json.Serialize(Model.t),
                },
                {
                    label: 'Температура газа',
                    data: @Json.Serialize(Model.T),
                },
                {
                    label: 'Разноссть температур',
                    data: @Json.Serialize(Model.diff_temp),
                }
            ]
        };

        const configLine = {
            type: 'line',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'График'
                    }
                }
            },
        };
        new Chart(ctx, configLine);
    </script>

}

Teploobmen/TeploobmenWeb/Views/Login/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Авторизация";
}

<form action ="/Login"method="post">
    @*Имя:
    <input name="Name" value="" autocomplete="off" />*@
    Email:
    <input name="Email" value="" autocomplete="off" />
    Пароль:
    <input type="password" name="" value="" autocomplete="off" />
    
    <button type="submit"> Войти</button>
</form>

Teploobmen/TeploobmenWeb/Views/Registr/Index.cshtml
@model TeploobmenInput
@{
    ViewData["Title"] = "Регистрация";
}

<form action="/Registr/" method="post">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div>
            <label asp-for="Email">Введите Email</label><br />
            <input type="text" asp-for="Email" />
            <span asp-validation-for="Email" />
        </div>
        <div>
            <label asp-for="Password">Введите пароль</label><br />
            <input asp-for="Password" />
            <span asp-validation-for="Password" />
        </div>

        <div>
            <input type="submit" value="Регистрация" />
        </div>
    </div>
</form>

Teploobmen/TeploobmenWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeploobmenWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeploobmenWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeploobmenWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Расчёт</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Выход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User">Личный кабинет</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login">Авторизация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Registr" asp-action="Index">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TeploobmenWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Teploobmen/TeploobmenWeb/Views/User/Index.cshtml
@model HomeIndexViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div>Привет, @User.Identity.Name!</div>